### ISSUE TITLE
你好，请教一个问题可以么。

### ISSUE THREAD

**Issue by Lockey-J** [coder-gao/Spider#4]
https://github.com/Lockey-J/Spider/blob/master/after.js。这种类型的应该如何还原下去呢。

**Comment by thouger** [comment]
问的很笼统，这里不止“这种”一一种类型吧。如果把这个文件看成一种类型，那就是用ast方法啊

**Comment by Lockey-J** [comment]
表达的有点问题。在56行的代码后，就变成类似字典的方式的变量。不知道要怎么再去消除优化他。

**Comment by thouger** [comment]
试试解开自执行函数，这里的字典通过形参传进去函数d那里了
